net-test: resilient_rs_test.py - slightly bump EPSILON
to deflake test when it hits errors like:
  self.assertLess(min_exp, t)
  AssertionError: 0.8 not less than 0.7886772155761719
which are happening just a little bit too often.

Test: ran against ACK 5.4-S, TreeHugger
Bug: 191826861
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Original-Change: https://android-review.googlesource.com/1742096
Merged-In: I9527b905660a07db39fca9944d129d0771be209f
Change-Id: I9527b905660a07db39fca9944d129d0771be209f